FROM node:10.12.0-alpine
LABEL maintainer="xLasercut"

ARG WORK_DIR=/home/picastclient

RUN apk update && apk upgrade \
 && apk -q add curl \
 && apk -q add bash \
 && apk -q add bash-completion \
 #install node packages
 && npm install -g http-server \
 #purge cache
 && rm -rf /var/cache/apk/* && \
 mkdir $WORK_DIR

WORKDIR $WORK_DIR

COPY dist $WORK_DIR/dist/.
COPY start.sh $WORK_DIR/.
COPY healthcheck.sh $WORK_DIR/.

EXPOSE ${PORT}

HEALTHCHECK --interval=1m30s --timeout=10s --retries=10 \
     CMD /bin/bash healthcheck.sh

CMD ["/bin/bash", "start.sh"]