version: '3'
services:
    picast-server:
        restart: unless-stopped
        build:
            context: ./server/
        environment:
            - HOST=0.0.0.0
            - PORT=8000
        ports:
            - 8000:8000
        volumes:
            - /opt/vc:/opt/vc
        devices:
            - /dev/vchiq:/dev/vchiq
            - /dev/fb0:/dev/fb0
    picast-client:
        restart: unless-stopped
        build:
            context: ./client/
        environment:
            - HOST=0.0.0.0
            - PORT=8001
            - REQUEST_HOST
        ports:
            - 8001:8001