version: '3'
services:
    picast-server:
        build:
            context: ./server/
        environment:
            - HOST=0.0.0.0
            - PORT=8000
        ports:
            - 8000:8000
    picast-client:
        build:
            context: ./client/
        environment:
            - HOST=0.0.0.0
            - PORT=8001
            - REQUEST_HOST
        ports:
            - 8001:8001