FROM lasercut/raspbian-stretch-lite:18-11-13
LABEL maintainer='xLasercut'

ARG WORK_DIR=/home/picastserver

ENV LOG_PATH $WORK_DIR/log/picast.log

COPY ./requirements.txt $WORK_DIR/requirements.txt

RUN apt-get update && \
 apt-get install -y \
 omxplayer\
 python3-pip &&\
 pip3 install -r $WORK_DIR/requirements.txt &&\
 mkdir $WORK_DIR/log

COPY . $WORK_DIR/.

WORKDIR $WORK_DIR

EXPOSE ${PORT}


CMD ["python3", "main.py"]