FROM lasercut/raspbian-stretch-lite:18-11-13
LABEL maintainer="xLasercut"

ARG WORK_DIR=/home/picastserver

ENV LOG_PATH $WORK_DIR/log/picast.log

COPY requirements.txt $WORK_DIR/requirements.txt

RUN apt-get update && \
 apt-get install -y \
 omxplayer\
 python3-pip &&\
 pip3 install -r $WORK_DIR/requirements.txt &&\
 mkdir $WORK_DIR/log

COPY . $WORK_DIR/.

WORKDIR $WORK_DIR

EXPOSE ${PORT}

HEALTHCHECK --interval=1m30s --timeout=10s --retries=10 \
    CMD curl --fail -X POST -H "Content-Type: application/json" -d '{"status": []}' http://$HOST:$PORT/status || exit 1

CMD ["python3", "-u", "main.py"]