FROM lasercut/raspbian-stretch-lite:18-11-13
LABEL maintainer='xLasercut'

ARG WORK_DIR='/home'

ENV LOG_PATH $WORK_DIR/log/picast.log

COPY ./requirements.txt $WORK_DIR/requirements.txt

RUN apt-get update && \
 apt-get install -y \
 omxplayer


CMD ['/bin/bash']